export { Login } from './Login'
export { Register } from './Register'
export { CourseView } from './CourseView'
export { Settings } from './Settings'
export { HomeView } from './HomeView'
export { Profile } from './Profile'
